# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('free', models.BooleanField(default=False)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pricings', to='events.Event')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_level', to='members.MembershipLevel')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
