# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('events', '0001_initial'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('spiresite', '0002_auto_20170608_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='FameGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fame_gallery_image', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HallOfFameOverviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('event_heading', models.CharField(blank=True, max_length=255)),
                ('page_content', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('gallery_caption', models.CharField(blank=True, max_length=255)),
                ('sponsors', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fame_event', to='events.Event')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='famegallery',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fame_gallery', to='spiresite.HallOfFameOverviewPage'),
        ),
    ]
