# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0003_auto_20170529_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sponsor_one_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_three_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_two_link',
            field=models.URLField(blank=True),
        ),
    ]
