# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0003_auto_20170322_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventIndexPage',
            new_name='EventsIndexPage',
        ),
    ]
