# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0004_famesponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halloffameoverviewpage',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='halloffameoverviewpage',
            name='sponsors_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
