# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('spiresite', '0004_auto_20170529_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='join_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='join_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_image', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='join_link',
            field=models.URLField(blank=True),
        ),
    ]
