# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0006_auto_20170529_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='page_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_one',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_three',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_two',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
