# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0007_auto_20170530_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='srecpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='srecpage',
            name='page_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
