# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0009_auto_20170609_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famebanquetgallery',
            name='featured_one',
        ),
        migrations.RemoveField(
            model_name='famebanquetgallery',
            name='featured_two',
        ),
        migrations.RemoveField(
            model_name='famebanquetgallery',
            name='page',
        ),
        migrations.RemoveField(
            model_name='famebanquetgalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='famebanquetgalleryimage',
            name='page',
        ),
        migrations.AddField(
            model_name='halloffamebanquetspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('image_block', wagtail.wagtailcore.blocks.StructBlock([(b'image_one', wagtail.wagtailimages.blocks.ImageChooserBlock(null=True)), (b'image_two', wagtail.wagtailimages.blocks.ImageChooserBlock(null=True))])), ('gallery_block', wagtail.wagtailcore.blocks.StructBlock([(b'caption', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'images', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(null=True))])))]))], null=True),
        ),
        migrations.DeleteModel(
            name='FameBanquetGallery',
        ),
        migrations.DeleteModel(
            name='FameBanquetGalleryImage',
        ),
    ]
