# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_featured'),
        ('spiresite', '0009_screcpagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_chooser', to='events.Event')),
            ],
        ),
    ]
