# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_featured'),
        ('spiresite', '0010_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='srecpage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.Event'),
        ),
    ]
