# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0012_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_box',
            field=wagtail.wagtailcore.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
