# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('spiresite', '0013_auto_20170609_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_email', models.EmailField(help_text=b'Address that contact form submissions will be sent to', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.CharField(help_text=b'Your Instagram url', max_length=255),
        ),
    ]
