# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0013_auto_20170530_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
        migrations.AlterField(
            model_name='srecpage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srec_event', to='events.Event'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
