# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0014_auto_20170609_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThemeMediaSettings',
            new_name='ThemeSettings',
        ),
    ]
