# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0016_srecmemberspage_srec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srecmemberspage',
            name='srec',
        ),
    ]
