# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0016_contactpage_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='contact_form_message',
            field=models.CharField(default='thank you', max_length=255),
            preserve_default=False,
        ),
    ]
