# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0017_remove_srecmemberspage_srec'),
    ]

    operations = [
        migrations.AddField(
            model_name='srecmemberspage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
