# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0020_auto_20170530_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='membershippage',
            name='page_content',
        ),
        migrations.AddField(
            model_name='membershippage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
