# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0022_jobpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='job_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
