# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0022_membershippage_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippage',
            name='full_friends_membership',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershippage',
            name='full_membership',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershippage',
            name='full_young_membership',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershippage',
            name='guest_membership',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershippage',
            name='student_membership',
            field=models.TextField(blank=True),
        ),
    ]
