# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0023_auto_20170610_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
