# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0023_auto_20170531_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippage',
            name='full_membership_button_5_year',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershippage',
            name='full_membership_button_year',
            field=models.TextField(blank=True),
        ),
    ]
