# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0024_auto_20170531_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippage',
            name='full_membership_button_5_year',
        ),
        migrations.RemoveField(
            model_name='membershippage',
            name='full_membership_button_year',
        ),
    ]
