# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_membershipproduct_subscription'),
        ('spiresite', '0025_auto_20170531_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippage',
            name='full_membership_yearly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srec_event', to='products.MembershipProduct'),
        ),
    ]
