# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0026_linkpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadershipstaffgallery',
            name='company',
        ),
        migrations.AddField(
            model_name='leadershipstaffgallery',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
