# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_membershipproduct_subscription'),
        ('spiresite', '0026_membershippage_full_membership_yearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippage',
            name='full_membership_5_years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_full_5_years', to='products.MembershipProduct'),
        ),
        migrations.AlterField(
            model_name='membershippage',
            name='full_membership_yearly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_full_year', to='products.MembershipProduct'),
        ),
    ]
