# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0027_auto_20170614_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpricing',
            name='price',
        ),
        migrations.AddField(
            model_name='eventpricing',
            name='event_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
    ]
