# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0028_auto_20170531_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(help_text=b'Icon CSS class', max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_benefits', to='spiresite.MembershipPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
