# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0029_auto_20170614_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpricing',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpricing',
            name='level',
        ),
        migrations.DeleteModel(
            name='EventPricing',
        ),
    ]
