# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('spiresite', '0029_membershipbenefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippage',
            name='member_closing',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershippage',
            name='people_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_image', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='membershippage',
            name='people_review_one',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershippage',
            name='people_review_two',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
