# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('spiresite', '0030_auto_20170614_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreports',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_image', to='wagtailimages.Image'),
        ),
    ]
