# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('spiresite', '0031_memberdirectorypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text=b'Your Facebook page URL')),
                ('instagram', models.CharField(help_text=b'Your Instagram username, without the @', max_length=255)),
                ('twitter', models.URLField(help_text=b'Your twitter page URL')),
                ('youtube', models.URLField(help_text=b'Your YouTube channel or user account URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
