# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0032_socialmediasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='youtube',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(default='twitter', help_text=b'Your Linkedin Profile URL'),
            preserve_default=False,
        ),
    ]
