# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_featured'),
        ('spiresite', '0033_auto_20170602_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_event', to='events.Event'),
        ),
    ]
