# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0034_homepage_featured_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='srecpage',
            name='gallery_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
