# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 21:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0035_auto_20170619_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffamestandardpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())]),
        ),
    ]
