# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('spiresite', '0037_leadershipstaffpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipStaffGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_gallery_image', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='leadershipstaffpage',
            name='body',
        ),
        migrations.AddField(
            model_name='leadershipstaffgallery',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_gallery', to='spiresite.LeadershipStaffPage'),
        ),
    ]
