# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0038_auto_20170606_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipstaffgallery',
            name='company',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadershipstaffgallery',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadershipstaffgallery',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
