# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 21:16
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0041_auto_20170606_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipregionalleaderspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('region', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('leader', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'company', wagtail.wagtailcore.blocks.CharBlock(required=True))])))]),
        ),
    ]
