# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0042_auto_20170619_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('posted_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
