# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0043_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='test', unique=True, verbose_name=b'Job URL'),
            preserve_default=False,
        ),
    ]
