# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('spiresite', '0044_standardpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncampuspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='OnCampusPage',
        ),
    ]
