# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0045_auto_20170620_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.URLField(default='test.com'),
            preserve_default=False,
        ),
    ]
