# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0048_themesettings_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_event', to='events.Event'),
        ),
    ]
