# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 22:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0055_membershippage_member_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
