# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
