# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-06 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpricinglevel',
            name='membership_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_level', to='members.MembershipLevel'),
        ),
    ]
