# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170322_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='event1'),
            preserve_default=False,
        ),
    ]
