# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventpricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpricing',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventpricing',
            name='sort_order',
        ),
    ]
