# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170516_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, default=6, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=4, verbose_name='Event URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=8, max_length=254),
            preserve_default=False,
        ),
    ]
