# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Description',
        ),
    ]
