# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 22:01
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170614_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpricing',
            name='event',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pricings', to='events.Event'),
        ),
    ]
