# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Description',
            field=wagtail.wagtailcore.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
    ]
