# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170614_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
