# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20170505_1939'),
        ('events', '0006_auto_20170505_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='members.Member'),
            preserve_default=False,
        ),
    ]
