# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20170328_0205'),
        ('events', '0006_eventmembershiplevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmembershiplevel',
            name='membership_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership_level', to='members.MembershipLevel'),
            preserve_default=False,
        ),
    ]
