# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProduct',
            fields=[
                ('sku', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_products', to='events.Event')),
            ],
        ),
    ]
