# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventattendance_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='members.Member'),
        ),
    ]
