# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventmembershiplevel_membership_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMembershipLevel',
            new_name='EventPricingLevel',
        ),
    ]
