# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproduct',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_products', to='events.Event'),
        ),
    ]
