# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170508_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_attendance', to='members.Member'),
        ),
    ]
