# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170719_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='San fransisco', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default=100, max_length=255),
            preserve_default=False,
        ),
    ]
