# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170511_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Location',
            new_name='location',
        ),
    ]
