# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 20:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170717_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproduct',
            name='event',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_products', to='events.Event'),
        ),
    ]
