# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170719_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GIFTS', 'Gifts/Students'), ('TRIBUTE', 'Tribute Ads')], default='TRIBUTE', max_length=50),
        ),
    ]
