# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SPONSORSHIP', 'Sponsorship'), ('GIFTS', 'Gifts/Students'), ('TRIBUTE', 'Tribute Ads')], default='TRIBUTE', max_length=50),
        ),
    ]
