# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-06 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=254)),
                ('phone_home', models.CharField(blank=True, max_length=254)),
                ('phone_prefered', models.CharField(blank=True, max_length=254)),
                ('membership_expiration', models.DateTimeField()),
                ('image', models.ImageField(default='/home/douglas/dev/repos/spire/spire/media/defaults/headshot.png', upload_to='members')),
                ('professional_address', models.TextField(blank=True)),
                ('professional_phone', models.CharField(blank=True, max_length=254)),
                ('professional_email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=254)),
                ('company_type', models.CharField(blank=True, max_length=254)),
                ('assistant_name', models.CharField(blank=True, max_length=254)),
                ('assistant_email', models.EmailField(blank=True, max_length=254)),
                ('assistant_phone', models.CharField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('skills_specialties', models.TextField(blank=True)),
                ('linkedIn', models.CharField(blank=True, max_length=254)),
                ('facebook', models.CharField(blank=True, max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('SEASONAL', 'Seasonal'), ('ONE_TIME', '1-time'), ('PREFERRED', 'Preferred')], max_length=50)),
                ('address', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('UNDERGRAD', 'Undergraduate'), ('MA', 'MA'), ('MS', 'MS'), ('MBA', 'MBA'), ('JD', 'JD'), ('PHD', 'PHD')], max_length=50)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('grad_year', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEventPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPGRADE', 'Upgrade'), ('DOWNGRADE', 'Downgrade')], max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='membership_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_levels', to='members.MembershipLevel'),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.ManyToManyField(related_name='member_regions', to='members.MemberRegion'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
