# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_expiration', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(default='/media/defaults/headshot.png', upload_to='members')),
                ('mobile_phone', models.CharField(blank=True, max_length=254)),
                ('work_phone', models.CharField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('skills_specialties', models.TextField(blank=True)),
                ('linkedIn', models.CharField(blank=True, max_length=254)),
                ('facebook', models.CharField(blank=True, max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('SEASONAL', 'Seasonal'), ('ONE_TIME', '1-time'), ('PREFERRED', 'Preferred')], max_length=50)),
                ('address_line_one', models.CharField(max_length=255)),
                ('address_line_two', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('UNDERGRAD', 'Undergraduate'), ('MA', 'MA'), ('MS', 'MS'), ('MBA', 'MBA'), ('JD', 'JD'), ('PHD', 'PHD')], max_length=50)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('grad_year', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MemberNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('cc_num_redacted', models.CharField(max_length=32, validators=[members.validators.validate_redacted])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('level', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPGRADE', 'Upgrade'), ('DOWNGRADE', 'Downgrade')], max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='industry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_industry', to='members.MemberIndustry'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_level',
            field=models.ForeignKey(blank=True, default='guest', on_delete=django.db.models.deletion.CASCADE, related_name='membership_levels', to='members.MembershipLevel'),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.ManyToManyField(related_name='member_regions', to='members.MemberRegion'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
