# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone_prefered',
            new_name='phone_preferred',
        ),
    ]
