# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiplevel',
            name='slug',
            field=models.SlugField(default='srec', unique=True),
            preserve_default=False,
        ),
    ]
