# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiplevel',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_level',
            field=models.ManyToManyField(related_name='membership_levels', to='members.MembershipLevel'),
        ),
    ]
