# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='defaults/headshot.png', upload_to='members'),
        ),
        migrations.AlterField(
            model_name='member',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_industry', to='members.MemberIndustry'),
        ),
    ]
