# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiplevel',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
