# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membershiplevel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofesionalinformation',
            name='title',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
