# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170322_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('SEASONAL', 'Seasonal'), ('ONE_TIME', '1-time'), ('PREFERRED', 'Preferred')], max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
