# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170516_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaddress',
            name='country',
            field=models.CharField(default='United States', max_length=255),
            preserve_default=False,
        ),
    ]
