# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170413_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
