# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170614_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiplevel',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Lookup field'),
        ),
    ]
