# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170413_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaddress',
            name='address_line1',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='city',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='state',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='zip_code',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_levels', to='members.MembershipLevel'),
        ),
    ]
