# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170413_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='assistant_email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='assistant_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='assistant_phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='company',
        ),
        migrations.RemoveField(
            model_name='member',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_home',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_preferred',
        ),
        migrations.RemoveField(
            model_name='member',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='professional_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='professional_email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='professional_phone',
        ),
    ]
