# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170519_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='industry',
        ),
        migrations.AddField(
            model_name='memberproffesionalinformation',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_industry', to='members.MemberIndustry'),
        ),
        migrations.AddField(
            model_name='memberproffesionalinformation',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professional_information', to='members.Member'),
            preserve_default=False,
        ),
    ]
