# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170425_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
