# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='media/defaults/headshot.png', upload_to='/media/member-images'),
        ),
    ]
