# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170620_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberaddress',
            name='address_type',
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_level',
            field=models.ForeignKey(blank=True, default='Guest', on_delete=django.db.models.deletion.CASCADE, related_name='membership_levels', to='members.MembershipLevel'),
        ),
    ]
