# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='cell_phone',
        ),
        migrations.AddField(
            model_name='member',
            name='work_phone',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
