# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20170620_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofesionalinformation',
            name='address_line_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberprofesionalinformation',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberprofesionalinformation',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberprofesionalinformation',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberprofesionalinformation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
