# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20170621_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='defaults/headshot.png', height_field=500, null=True, upload_to='members'),
        ),
    ]
