# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20170519_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberProffesionalInformation',
            new_name='MemberProfesionalInformation',
        ),
    ]
