# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20170426_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
