# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiplevel',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_level',
            field=models.ForeignKey(blank=True, default='GUEST', on_delete=django.db.models.deletion.CASCADE, related_name='membership_levels', to='members.MembershipLevel'),
        ),
        migrations.AlterField(
            model_name='membershiplevel',
            name='level',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
