# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20170624_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='defaults/headshot.png', null=True, upload_to='members'),
        ),
    ]
