# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20170327_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='assistant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='assistant_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='assistant_phone',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='company',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='company_type',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='professional_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='professional_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='professional_phone',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='skills_specialties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.OneToOneField(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='members.MemberRegion'),
            preserve_default=False,
        ),
    ]
