# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20170626_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpurchasehistory',
            name='cc_num_redacted',
        ),
    ]
