# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20170327_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='region',
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.ManyToManyField(related_name='member_regions', to='members.MemberRegion'),
        ),
    ]
