# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20170427_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_level',
            field=models.ForeignKey(blank=True, default='guest', on_delete=django.db.models.deletion.CASCADE, related_name='membership_levels', to='members.MembershipLevel'),
        ),
    ]
