# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_memberpurchasehistory_cc_num_redacted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='linkedIn',
            new_name='linkedin',
        ),
    ]
