# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20170505_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='/media/defaults/headshot.png', upload_to='members'),
        ),
        migrations.AlterField(
            model_name='memberaddress',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='members.Member'),
        ),
    ]
