# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_memberdegree'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdegree',
            name='program',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
