# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_membermembershiphistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermembershiphistory',
            name='level',
        ),
        migrations.AddField(
            model_name='membermembershiphistory',
            name='new_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_level', to='members.MembershipLevel'),
        ),
        migrations.AddField(
            model_name='membermembershiphistory',
            name='previous_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_level', to='members.MembershipLevel'),
        ),
    ]
