# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_memberdegree_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership_level',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_level',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='membership_levels', to='members.MembershipLevel'),
            preserve_default=False,
        ),
    ]
