# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_remove_memberaddress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberaddress',
            old_name='address_line1',
            new_name='address_line_one',
        ),
        migrations.RenameField(
            model_name='memberaddress',
            old_name='address_line2',
            new_name='address_line_two',
        ),
    ]
