# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20170626_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Short description of what this tag is for')),
            ],
        ),
        migrations.AddField(
            model_name='membernote',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.MemberTag'),
        ),
    ]
