# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20170505_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberEventPurchase',
            new_name='MemberPurchaseHistory',
        ),
    ]
