# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20170628_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membernote',
            name='tag',
        ),
        migrations.AddField(
            model_name='membernote',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='members.MemberTag'),
        ),
    ]
