# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20170505_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpurchasehistory',
            name='event',
        ),
        migrations.AddField(
            model_name='memberpurchasehistory',
            name='item',
            field=models.CharField(default='Event', max_length=255),
            preserve_default=False,
        ),
    ]
