# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import members.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20170505_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpurchasehistory',
            name='cc_num_redacted',
            field=models.CharField(default='1111********1111', max_length=16, validators=[members.validators.validate_redacted]),
            preserve_default=False,
        ),
    ]
