# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20170704_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernote',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='members.MemberTag'),
        ),
    ]
