# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import members.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_memberpurchasehistory_cc_num_redacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpurchasehistory',
            name='cc_num_redacted',
            field=models.CharField(max_length=32, validators=[members.validators.validate_redacted]),
        ),
    ]
