# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20170704_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membertag',
            old_name='tag',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='membertag',
            name='description',
        ),
        migrations.AddField(
            model_name='membertag',
            name='label',
            field=models.CharField(default='important', help_text='Tag Label', max_length=100),
            preserve_default=False,
        ),
    ]
