# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20170704_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='membernote',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='membertag',
            name='label',
        ),
        migrations.RemoveField(
            model_name='membertag',
            name='value',
        ),
        migrations.AddField(
            model_name='membertag',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='members.MemberNote'),
        ),
        migrations.AddField(
            model_name='membertag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.AvailableTags'),
        ),
    ]
