# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20170328_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_expiration',
            field=models.DateTimeField(),
        ),
    ]
