# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_membernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernote',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
