# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 23:16
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('members', '0020_auto_20170704_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membertag',
            name='note',
        ),
        migrations.RemoveField(
            model_name='membertag',
            name='tag',
        ),
        migrations.AddField(
            model_name='membernote',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='AvailableTags',
        ),
        migrations.DeleteModel(
            name='MemberTag',
        ),
    ]
