# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20170704_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofesionalinformation',
            name='industry',
            field=models.TextField(default='Forestry'),
            preserve_default=False,
        ),
    ]
