# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_memberindustry_entered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiplevel',
            name='expires',
            field=models.BooleanField(default=True),
        ),
    ]
