# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20170705_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofesionalinformation',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_industry', to='members.MemberIndustry'),
        ),
    ]
