# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20170510_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='industry',
        ),
    ]
