# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_membershiplevel_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiplevel',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
