# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_auto_20170719_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermembershiphistory',
            options={'verbose_name': 'Membership Level history', 'verbose_name_plural': 'Membership Level history'},
        ),
    ]
