# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproduct',
            name='name',
            field=models.CharField(default='SREC', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipproduct',
            name='name',
            field=models.CharField(default='tes', max_length=255),
            preserve_default=False,
        ),
    ]
