# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170530_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipproduct',
            name='membership_length',
            field=models.IntegerField(default=1, help_text='Length In Years'),
            preserve_default=False,
        ),
    ]
