# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_capacity'),
        ('products', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='general_product', to='events.Event'),
            preserve_default=False,
        ),
    ]
