# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiresite', '0028_auto_20170531_0033'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('products', '0005_membershipcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipcart',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='MembershipCart',
        ),
    ]
