# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_products', to='events.Event'),
        ),
    ]
