# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170717_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='event',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
